version: "3.8"
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - COMPOSE_DOCKER_CLI_BUILD=1
      - DOCKER_BUILDKIT=1
      - NODE_ENV=development
      - DEBUG=chess-app:*
