export default [
    { type: 'rei', valuePositions: [
      { position: 'x0y0', value: 0.0 },
      { position: 'x0y1', value: 0.0 },
      { position: 'x0y2', value: 0.0 },
      { position: 'x0y3', value: 0.0 },
      { position: 'x0y4', value: 0.0 },
      { position: 'x0y5', value: 0.0 },
      { position: 'x0y6', value: 0.0 },
      { position: 'x0y7', value: 0.0 },
  
      { position: 'x1y0', value: 0.0 },
      { position: 'x1y1', value: 0.0 },
      { position: 'x1y2', value: 0.0 },
      { position: 'x1y3', value: 0.0 },
      { position: 'x1y4', value: 0.0 },
      { position: 'x1y5', value: 0.0 },
      { position: 'x1y6', value: 0.0 },
      { position: 'x1y7', value: 0.0 },
      
      { position: 'x2y0', value: 0.0 },
      { position: 'x2y1', value: 0.0 },
      { position: 'x2y2', value: 0.0 },
      { position: 'x2y3', value: 0.0 },
      { position: 'x2y4', value: 0.0 },
      { position: 'x2y5', value: 0.0 },
      { position: 'x2y6', value: 0.0 },
      { position: 'x2y7', value: 0.0 },
  
      { position: 'x3y0', value: 0.0 },
      { position: 'x3y1', value: 0.0 },
      { position: 'x3y2', value: 0.0 },
      { position: 'x3y3', value: 0.0 },
      { position: 'x3y4', value: 0.0 },
      { position: 'x3y5', value: 0.0 },
      { position: 'x3y6', value: 0.0 },
      { position: 'x3y7', value: 0.0 },
  
      { position: 'x4y0', value: 0.0 },
      { position: 'x4y1', value: 0.0 },
      { position: 'x4y2', value: 0.0 },
      { position: 'x4y3', value: 0.0 },
      { position: 'x4y4', value: 0.0 },
      { position: 'x4y5', value: 0.0 },
      { position: 'x4y6', value: 0.0 },
      { position: 'x4y7', value: 0.0 },
  
      { position: 'x5y0', value: 0.0 },
      { position: 'x5y1', value: 0.0 },
      { position: 'x5y2', value: 0.0 },
      { position: 'x5y3', value: 0.0 },
      { position: 'x5y4', value: 0.0 },
      { position: 'x5y5', value: 0.0 },
      { position: 'x5y6', value: 0.0 },
      { position: 'x5y7', value: 0.0 },
  
      { position: 'x6y0', value: 0.0 },
      { position: 'x6y1', value: 0.0 },
      { position: 'x6y2', value: 0.0 },
      { position: 'x6y3', value: 0.0 },
      { position: 'x6y4', value: 0.0 },
      { position: 'x6y5', value: 0.0 },
      { position: 'x6y6', value: 0.0 },
      { position: 'x6y7', value: 0.0 },
  
      { position: 'x7y0', value: 0.0 },
      { position: 'x7y1', value: 0.0 },
      { position: 'x7y2', value: 0.0 },
      { position: 'x7y3', value: 0.0 },
      { position: 'x7y4', value: 0.0 },
      { position: 'x7y5', value: 0.0 },
      { position: 'x7y6', value: 0.0 },
      { position: 'x7y7', value: 0.0 },
  
    ]},
    { type: 'rainha', valuePositions: [
      { position: 'x0y0', value: 2.0 },
      { position: 'x0y1', value: 1.0 },
      { position: 'x0y2', value: 1.0 },
      { position: 'x0y3', value: 0.5 },
      { position: 'x0y4', value: 0.5 },
      { position: 'x0y5', value: 1.0 },
      { position: 'x0y6', value: 1.0 },
      { position: 'x0y7', value: 2.0 },
  
      { position: 'x1y0', value: 1.0 },
      { position: 'x1y1', value: 0.0 },
      { position: 'x1y2', value: -0.5 },
      { position: 'x1y3', value: 0.0 },
      { position: 'x1y4', value: 0.0 },
      { position: 'x1y5', value: 0.0 },
      { position: 'x1y6', value: 0.0 },
      { position: 'x1y7', value: 1.0 },
      
      { position: 'x2y0', value: 1.0 },
      { position: 'x2y1', value: -0.5 },
      { position: 'x2y2', value: -0.5 },
      { position: 'x2y3', value: -0.5 },
      { position: 'x2y4', value: -0.5 },
      { position: 'x2y5', value: -0.5 },
      { position: 'x2y6', value: 0.0 },
      { position: 'x2y7', value: 1.0 },
  
      { position: 'x3y0', value: 0.0 },
      { position: 'x3y1', value: 0.0 },
      { position: 'x3y2', value: -0.5 },
      { position: 'x3y3', value: -0.5 },
      { position: 'x3y4', value: -0.5 },
      { position: 'x3y5', value: -0.5 },
      { position: 'x3y6', value: 0.0 },
      { position: 'x3y7', value: 0.5 },
  
      { position: 'x4y0', value: 0.5 },
      { position: 'x4y1', value: 0.0 },
      { position: 'x4y2', value: -0.5 },
      { position: 'x4y3', value: -0.5 },
      { position: 'x4y4', value: -0.5 },
      { position: 'x4y5', value: -0.5 },
      { position: 'x4y6', value: 0.0 },
      { position: 'x4y7', value: 0.5 },
  
      { position: 'x5y0', value: 1.0 },
      { position: 'x5y1', value: 0.0 },
      { position: 'x5y2', value: -0.5 },
      { position: 'x5y3', value: -0.5 },
      { position: 'x5y4', value: -0.5 },
      { position: 'x5y5', value: -0.5 },
      { position: 'x5y6', value: 0.0 },
      { position: 'x5y7', value: 1.0 },
  
      { position: 'x6y0', value: 1.0 },
      { position: 'x6y1', value: 0.0 },
      { position: 'x6y2', value: 0.0 },
      { position: 'x6y3', value: 0.0 },
      { position: 'x6y4', value: 0.0 },
      { position: 'x6y5', value: 0.0 },
      { position: 'x6y6', value: 0.0 },
      { position: 'x6y7', value: 1.0 },
  
      { position: 'x7y0', value: 2.0 },
      { position: 'x7y1', value: 1.0 },
      { position: 'x7y2', value: 1.0 },
      { position: 'x7y3', value: 0.5 },
      { position: 'x7y4', value: 0.5 },
      { position: 'x7y5', value: 1.0 },
      { position: 'x7y6', value: 1.0 },
      { position: 'x7y7', value: 2.0 },
    ]},
    { type: 'torre', valuePositions: [
      { position: 'x0y0', value: 2.0 },
      { position: 'x0y1', value: 0.0 },
      { position: 'x0y2', value: 0.0 },
      { position: 'x0y3', value: 0.0 },
      { position: 'x0y4', value: 0.0 },
      { position: 'x0y5', value: 0.0 },
      { position: 'x0y6', value: 0.0 },
      { position: 'x0y7', value: 2.0 },
  
      { position: 'x1y0', value: 0.5 },
      { position: 'x1y1', value: 0.0 },
      { position: 'x1y2', value: 0.0 },
      { position: 'x1y3', value: 0.0 },
      { position: 'x1y4', value: 0.0 },
      { position: 'x1y5', value: 0.0 },
      { position: 'x1y6', value: 0.0 },
      { position: 'x1y7', value: 0.5 },
      
      { position: 'x2y0', value: 0.5 },
      { position: 'x2y1', value: 0.0 },
      { position: 'x2y2', value: 0.0 },
      { position: 'x2y3', value: 0.0 },
      { position: 'x2y4', value: 0.0 },
      { position: 'x2y5', value: 0.0 },
      { position: 'x2y6', value: 0.0 },
      { position: 'x2y7', value: 0.5 },
  
      { position: 'x3y0', value: 0.5 },
      { position: 'x3y1', value: 0.0 },
      { position: 'x3y2', value: 0.0 },
      { position: 'x3y3', value: 0.0 },
      { position: 'x3y4', value: 0.0 },
      { position: 'x3y5', value: 0.0 },
      { position: 'x3y6', value: 0.0 },
      { position: 'x3y7', value: 0.5 },
  
      { position: 'x4y0', value: 0.5 },
      { position: 'x4y1', value: 0.0 },
      { position: 'x4y2', value: 0.0 },
      { position: 'x4y3', value: 0.0 },
      { position: 'x4y4', value: 0.0 },
      { position: 'x4y5', value: 0.0 },
      { position: 'x4y6', value: 0.0 },
      { position: 'x4y7', value: 0.5 },
  
      { position: 'x5y0', value: 0.5 },
      { position: 'x5y1', value: 0.0 },
      { position: 'x5y2', value: 0.0 },
      { position: 'x5y3', value: 0.0 },
      { position: 'x5y4', value: 0.0 },
      { position: 'x5y5', value: 0.0 },
      { position: 'x5y6', value: 0.0 },
      { position: 'x5y7', value: 1.0 },
  
      { position: 'x6y0', value: 1.0 },
      { position: 'x6y1', value: 0.0 },
      { position: 'x6y2', value: 0.0 },
      { position: 'x6y3', value: 0.0 },
      { position: 'x6y4', value: 0.0 },
      { position: 'x6y5', value: 0.0 },
      { position: 'x6y6', value: 0.0 },
      { position: 'x6y7', value: 1.0 },
  
      { position: 'x7y0', value: 1.0 },
      { position: 'x7y1', value: 1.0 },
      { position: 'x7y2', value: 1.0 },
      { position: 'x7y3', value: 0.5 },
      { position: 'x7y4', value: 0.5 },
      { position: 'x7y5', value: 1.0 },
      { position: 'x7y6', value: 1.0 },
      { position: 'x7y7', value: 1.0 },
    ]},
    { type: 'bispo', valuePositions: [
      { position: 'x0y0', value: 2.0 },
      { position: 'x0y1', value: 1.0 },
      { position: 'x0y2', value: 1.0 },
      { position: 'x0y3', value: 1.0 },
      { position: 'x0y4', value: 1.0 },
      { position: 'x0y5', value: 1.0 },
      { position: 'x0y6', value: 1.0 },
      { position: 'x0y7', value: 2.0 },
  
      { position: 'x1y0', value: 1.5 },
      { position: 'x1y1', value: 0.5 },
      { position: 'x1y2', value: 0.0 },
      { position: 'x1y3', value: 0.0 },
      { position: 'x1y4', value: 0.0 },
      { position: 'x1y5', value: 0.0 },
      { position: 'x1y6', value: 1.0 },
      { position: 'x1y7', value: 1.5 },
      
      { position: 'x2y0', value: 1.5 },
      { position: 'x2y1', value: 1.0 },
      { position: 'x2y2', value: 1.0 },
      { position: 'x2y3', value: 1.0 },
      { position: 'x2y4', value: 1.0 },
      { position: 'x2y5', value: 1.0 },
      { position: 'x2y6', value: 1.0 },
      { position: 'x2y7', value: 1.0 },
  
      { position: 'x3y0', value: 1.0 },
      { position: 'x3y1', value: 0.0 },
      { position: 'x3y2', value: 1.0 },
      { position: 'x3y3', value: 1.0 },
      { position: 'x3y4', value: 1.0 },
      { position: 'x3y5', value: 1.0 },
      { position: 'x3y6', value: 1.0 },
      { position: 'x3y7', value: 1.0 },
  
      { position: 'x4y0', value: 1.0 },
      { position: 'x4y1', value: 1.0 },
      { position: 'x4y2', value: 1.0 },
      { position: 'x4y3', value: 1.0 },
      { position: 'x4y4', value: 1.0 },
      { position: 'x4y5', value: 0.0 },
      { position: 'x4y6', value: 0.0 },
      { position: 'x4y7', value: 0.5 },
  
      { position: 'x5y0', value: 1.5 },
      { position: 'x5y1', value: 1.0 },
      { position: 'x5y2', value: 1.0 },
      { position: 'x5y3', value: 1.0 },
      { position: 'x5y4', value: 1.0 },
      { position: 'x5y5', value: 1.0 },
      { position: 'x5y6', value: 1.0 },
      { position: 'x5y7', value: 1.0 },
  
      { position: 'x6y0', value: 1.0 },
      { position: 'x6y1', value: 0.0 },
      { position: 'x6y2', value: 0.0 },
      { position: 'x6y3', value: 0.0 },
      { position: 'x6y4', value: 0.0 },
      { position: 'x6y5', value: 0.0 },
      { position: 'x6y6', value: 0.0 },
      { position: 'x6y7', value: 1.0 },
  
      { position: 'x7y0', value: 2.0 },
      { position: 'x7y1', value: 0.0 },
      { position: 'x7y2', value: 0.0 },
      { position: 'x7y3', value: 0.5 },
      { position: 'x7y4', value: 0.5 },
      { position: 'x7y5', value: 0.0 },
      { position: 'x7y6', value: 0.0 },
      { position: 'x7y7', value: 2.0 },
    ]},
    { type: 'cavalo', valuePositions: [
      { position: 'x0y0', value: -5.0 },
      { position: 'x0y1', value: -4.0 },
      { position: 'x0y2', value: -3.0 },
      { position: 'x0y3', value: -3.0 },
      { position: 'x0y4', value: -3.0 },
      { position: 'x0y5', value: -3.0 },
      { position: 'x0y6', value: -4.0 },
      { position: 'x0y7', value: -5.0 },
  
      { position: 'x1y0', value: -4.5 },
      { position: 'x1y1', value: -2.5 },
      { position: 'x1y2', value: 0.0 },
      { position: 'x1y3', value: 0.0 },
      { position: 'x1y4', value: 0.0 },
      { position: 'x1y5', value: 0.0 },
      { position: 'x1y6', value: -2.0 },
      { position: 'x1y7', value: -4.5 },
      
      { position: 'x2y0', value: 3.5 },
      { position: 'x2y1', value: 0.0 },
      { position: 'x2y2', value: 1.0 },
      { position: 'x2y3', value: -1.5 },
      { position: 'x2y4', value: -1.5 },
      { position: 'x2y5', value: 1.0 },
      { position: 'x2y6', value: 1.0 },
      { position: 'x2y7', value: 3.0 },
  
      { position: 'x3y0', value: 1.0 },
      { position: 'x3y1', value: 0.0 },
      { position: 'x3y2', value: 1.0 },
      { position: 'x3y3', value: 1.0 },
      { position: 'x3y4', value: 1.0 },
      { position: 'x3y5', value: 1.0 },
      { position: 'x3y6', value: 1.0 },
      { position: 'x3y7', value: 1.0 },
  
      { position: 'x4y0', value: 1.0 },
      { position: 'x4y1', value: 1.0 },
      { position: 'x4y2', value: 1.0 },
      { position: 'x4y3', value: 1.0 },
      { position: 'x4y4', value: 1.0 },
      { position: 'x4y5', value: 0.0 },
      { position: 'x4y6', value: 0.0 },
      { position: 'x4y7', value: 0.5 },
  
      { position: 'x5y0', value: 1.5 },
      { position: 'x5y1', value: 1.0 },
      { position: 'x5y2', value: 1.0 },
      { position: 'x5y3', value: 5.0 },
      { position: 'x5y4', value: 4.0 },
      { position: 'x5y5', value: 1.0 },
      { position: 'x5y6', value: 1.0 },
      { position: 'x5y7', value: 1.0 },
  
      { position: 'x6y0', value: -1.0 },
      { position: 'x6y1', value: 0.0 },
      { position: 'x6y2', value: 0.0 },
      { position: 'x6y3', value: 0.0 },
      { position: 'x6y4', value: 0.0 },
      { position: 'x6y5', value: 0.0 },
      { position: 'x6y6', value: 0.0 },
      { position: 'x6y7', value: -1.0 },
  
      { position: 'x7y0', value: -2.0 },
      { position: 'x7y1', value: -1.0 },
      { position: 'x7y2', value: -1.0 },
      { position: 'x7y3', value: -1.5 },
      { position: 'x7y4', value: -1.5 },
      { position: 'x7y5', value: -1.0 },
      { position: 'x7y6', value: -1.0 },
      { position: 'x7y7', value: -2.0 },
    ]},
    { type: 'peao', valuePositions: [
      { position: 'x0y0', value: -5.0 },
      { position: 'x0y1', value: -4.0 },
      { position: 'x0y2', value: -3.0 },
      { position: 'x0y3', value: -3.0 },
      { position: 'x0y4', value: -3.0 },
      { position: 'x0y5', value: -3.0 },
      { position: 'x0y6', value: -4.0 },
      { position: 'x0y7', value: -5.0 },
  
      { position: 'x1y0', value: -4.5 },
      { position: 'x1y1', value: -2.5 },
      { position: 'x1y2', value: 0.0 },
      { position: 'x1y3', value: 0.0 },
      { position: 'x1y4', value: 0.0 },
      { position: 'x1y5', value: 0.0 },
      { position: 'x1y6', value: -2.0 },
      { position: 'x1y7', value: -4.5 },
      
      { position: 'x2y0', value: 3.5 },
      { position: 'x2y1', value: 0.0 },
      { position: 'x2y2', value: 1.0 },
      { position: 'x2y3', value: -1.5 },
      { position: 'x2y4', value: -1.5 },
      { position: 'x2y5', value: 1.0 },
      { position: 'x2y6', value: 1.0 },
      { position: 'x2y7', value: 3.0 },
  
      { position: 'x3y0', value: 1.0 },
      { position: 'x3y1', value: 0.0 },
      { position: 'x3y2', value: 1.0 },
      { position: 'x3y3', value: 1.0 },
      { position: 'x3y4', value: 1.0 },
      { position: 'x3y5', value: 1.0 },
      { position: 'x3y6', value: 1.0 },
      { position: 'x3y7', value: 1.0 },
  
      { position: 'x4y0', value: 1.0 },
      { position: 'x4y1', value: 1.0 },
      { position: 'x4y2', value: 1.0 },
      { position: 'x4y3', value: 1.0 },
      { position: 'x4y4', value: 1.0 },
      { position: 'x4y5', value: 0.0 },
      { position: 'x4y6', value: 0.0 },
      { position: 'x4y7', value: 0.5 },
  
      { position: 'x5y0', value: 1.5 },
      { position: 'x5y1', value: 1.0 },
      { position: 'x5y2', value: 1.0 },
      { position: 'x5y3', value: 5.0 },
      { position: 'x5y4', value: 4.0 },
      { position: 'x5y5', value: 1.0 },
      { position: 'x5y6', value: 1.0 },
      { position: 'x5y7', value: 1.0 },
  
      { position: 'x6y0', value: -1.0 },
      { position: 'x6y1', value: 0.0 },
      { position: 'x6y2', value: 0.0 },
      { position: 'x6y3', value: 0.0 },
      { position: 'x6y4', value: 0.0 },
      { position: 'x6y5', value: 0.0 },
      { position: 'x6y6', value: 0.0 },
      { position: 'x6y7', value: -1.0 },
  
      { position: 'x7y0', value: -2.0 },
      { position: 'x7y1', value: -1.0 },
      { position: 'x7y2', value: -1.0 },
      { position: 'x7y3', value: -1.5 },
      { position: 'x7y4', value: -1.5 },
      { position: 'x7y5', value: -1.0 },
      { position: 'x7y6', value: -1.0 },
      { position: 'x7y7', value: -2.0 },
    ]},
  ];