name: Unit Tests

on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker
        run: |
          make build

      - name: Run Tests
        run: |
          make test
